[project]
name = "thus-17jul"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "openai-agents>=0.2.1",
    "python-decouple>=3.8",
]
